export const SET_CITY = "SET_CITY";
export const GET_CITIES = "GET_CITIES";
export const GET_CITY = "GET_CITY";
export const GET_FORECAST = "GET_FORECAST";
export const SET_FORECAST = "SET_FORECAST";

export const FETCH_FORECAST_BEGIN   = 'FETCH_FORECAST_BEGIN';
export const FETCH_FORECAST_SUCCESS = 'FETCH_FORECAST_SUCCESS';
export const FETCH_FORECAST_ERROR = 'FETCH_FORECAST_FAILURE';